app/urls.py
from django.urls import path
from . import views 
 

urlpatterns = [
    path('',views.homePage,name="home"),
    path('register/', views.register_user, name="register_user"),
    path('login/', views.login_user, name="login_user"),
    path('post/<slug:slug>/', views.post_detail, name='post_detail'),
    path('edit/<slug:slug>/', views.edit_post, name='edit_post'),
    path('create/', views.create_post, name='create_post'),
    path('logout/', views.my_logout, name='logout'),
    path('delete-post/<slug:slug>/', views.delete_post, name='delete_post'),
    path('searched-post/<slug:slug>/',views.search_posts, name='search_posts'),
]

forum/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("app.urls"), name="app-urls"),
    path('test/', include("testApp.urls"), name="test-urls")
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.utils.text import slugify
from django.db import models  
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from ckeditor.fields import RichTextField
import random

class CustomUser(AbstractUser): 
    date_of_birth = models.DateField(null=True, blank=True)
    profile_picture = models.ImageField(upload_to='profile_pics/', null=True, blank=True)
 
    
    def __str__(self):
        return self.username
    
    
class Post(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, related_name="post_author"
    )
    updated_on = models.DateTimeField(auto_now=True)
    content = RichTextField()
    attachment = models.FileField(upload_to='post_attachments/', null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)  

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("post_detail", kwargs={"slug": str(self.slug)})
    

    def create_unique_slug(self, new_slug=None):
        if new_slug is not None:
            slug = new_slug
        else:
            slug = slugify(self.title)

        queryset = Post.objects.filter(slug=slug).exclude(id=self.id)
        if queryset.exists():
            random_number = random.randint(1, 1000)
            new_slug = f"{slug}-{random_number}"
            return self.create_unique_slug(new_slug=new_slug)
        return slug
 


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, related_name="comments"
    )
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True) 

    class Meta:
        ordering = ["created_on"]

    def __str__(self): 
        return "Comment {} by {}".format(self.body, self.author.username)

app/forms.py
from django import forms
from ckeditor.fields import RichTextField
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser, Comment, Post

class CustomUserCreationForm(UserCreationForm):
    date_of_birth = forms.DateField(required=False)
    profile_picture = forms.ImageField(required=False) 
    
    class Meta:
        model = CustomUser
        fields = UserCreationForm.Meta.fields + ('date_of_birth', 'profile_picture')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["body"]


class PostForm(forms.ModelForm):
    content = RichTextField(config_name='awesome_ckeditor')
    class Meta:
        model = Post
        fields = ['title', 'content','attachment']

class SearchForm(forms.Form):
    query = forms.CharField(label='Search')

app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html> 
    <head>
        <title>Forum</title>
        <link rel="stylesheet" href="{% static 'css/base.css' %}">

        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
            integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />
        <style> 

        </style>

    </head>

    <body>


        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'home' %}">Forum</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
    
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto ">
                        {% if user_authenticated %}
                        <li class="nav-item text-black text-center">
                            <a class="nav-link text-black font-weight-bold" href="{% url 'create_post' %}">Create a
                                Post</a>
                        </li>
                        <li class="nav-item text-black text-center">
                            <a class="nav-link text-black font-weight-bold" href="#">{{ user.username }}</a>
                        </li>
                        <li class="nav-item text-black text-center">
                            <a class="nav-link text-black font-weight-bold" href="{% url 'logout' %}">Logout</a>
                        </li>
                        {% else %}
                        <li class="nav-item text-black text-center">
                            <a class="nav-link text-black font-weight-bold" href="{% url 'login_user' %}">Login</a>
                        </li>
                        <li class="nav-item text-black text-center">
                            <a class="nav-link text-black font-weight-bold" href="{% url 'register_user' %}">Signup</a>
                        </li>
                        {% endif %}
                    </ul> 
                </div>
            </div>
        </nav>


    {% block content %}
        <!-- Content Goes here -->
    {% endblock content %}

    <!-- Footer -->
    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
    </script>
</body>




</html>

app/templates/create_post.html
{% extends 'base.html' %}

{% block content %}
    
<div class="container" style="display: flex; flex-direction: row;">
    <div class="row">
        <div class="col-md-12 card mb-4  mt-3 left  top" style="align-items: left;">
            <div class="card-body">
                    {% if user_authenticated  %} 
                    <h1>Create Post</h1>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        {{ form.media }}
                        <button type="submit">Post</button>
                    </form enctype="multipart/form-data">
                    {# Include CKEditor assets #}
                    {% else %}
                    <h2>You are not Logged in!</h2>
                    <p class="card-title">Please <a href="{% url 'login_user' %}">Login</a> with correct user</p>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-md-4" style="display: none;">
            <div id="card" class="card-body right top"> 
            </div>
        </div>
    </div>

    <script>
        let titleInput = document.getElementById("id_title");
    
        titleInput.addEventListener("blur", async function (event) {
            let title = titleInput.value;
            try {
                const response = await fetch(`/searched-post/${title}`, {
                    method: "GET",
                    headers: {
                        "Content-Type": "application/json",
                    },
                });
                if (!response.ok) {
                    throw new Error("Network response was not ok");
                }
                const data = await response.json();
                const card = document.getElementById('card');
                if(data.length != 0){
                    card.parentElement.style.display = 'block';
                }
                else {
                    card.parentElement.style.display = 'none';
                }
     
                card.innerHTML = "";       
                await data.map((item) => { 
                    var itemDiv = document.createElement('a');
                    itemDiv.href = `/post/${item.slug}`;
                    var titleElement = document.createElement('h2');
                    titleElement.textContent = item.title;
                    itemDiv.appendChild(titleElement); 
                    var updatedOnElement = document.createElement('p');
                    updatedOnElement.style.borderBottom = '1px solid #333';
                    updatedOnElement.textContent = 'Updated on: ' + item.updated_on;
                    itemDiv.appendChild(updatedOnElement);
                    updatedOnElement.style.color = 'black';
                    titleElement.style.color = 'black';
                    itemDiv.style.textDecoration = 'none';
                    card.appendChild(itemDiv);
                }); 
            } catch (error) {
                console.error("Error fetching data:", error);
            }
        });
    </script>

{% endblock %}

app/templates/edit_post.html
{% extends 'base.html' %} {% block content %}
<div class="container" style="display: flex; flex-direction: row; text-decoration: none;">
    <div class="row">
        <div class="col-md-12 card mb-4  mt-3 left  top" style="align-items: left;">
            <div class="card-body">
                    {% if user_authenticated and post.author == request.user %}
                    <h1>Edit Post</h1>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %} {{ form.as_p }}
                        <button type="submit">Save changes</button>
                        <button
                            type="button"
                            id="delete"
                            onclick="deletePost('{{ post.slug }}')"
                        >
                            Delete Post
                        </button>
                    </form>
                    {# Include CKEditor assets #} {{ form.media }} {% else %}
                    <h2>You are not the author of the Post</h2>
                    <p class="card-title">
                        Please <a href="{% url 'login_user' %}">Login</a> with
                        correct user
                    </p>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-md-4" style="display: none;">
            <div id="card" class="card-body right top"> 
            </div>
        </div>
    </div>
<script>
    let titleInput = document.getElementById("id_title");

    titleInput.addEventListener("blur", async function (event) {
        let title = titleInput.value;
        try {
            const response = await fetch(`/searched-post/${title}`, {
                method: "GET",
                headers: {
                    "Content-Type": "application/json",
                },
            });
            if (!response.ok) {
                throw new Error("Network response was not ok");
            }
            const data = await response.json();
 
            const card = document.getElementById('card');
            if(data.length != 0){
                card.parentElement.style.display = 'block';
            }
            else {
                card.parentElement.style.display = 'none';
            }
            card.innerHTML = "";       
            await data.map((item) => { 
                var itemDiv = document.createElement('a');
                itemDiv.href = `/post/${item.slug}`;
                var titleElement = document.createElement('h2');
                titleElement.textContent = item.title;
                itemDiv.appendChild(titleElement); 
                var updatedOnElement = document.createElement('p');
                updatedOnElement.style.borderBottom = '1px solid #333';
                updatedOnElement.textContent = 'Updated on: ' + item.updated_on;
                itemDiv.appendChild(updatedOnElement);
                updatedOnElement.style.color = 'black';
                titleElement.style.color = 'black';
                itemDiv.style.textDecoration = 'none';
                card.appendChild(itemDiv);
            }); 
        } catch (error) {
            console.error("Error fetching data:", error);
        }
    });

    async function deletePost(slug) {
        if (confirm("Are you sure you want to delete this post?")) {
            await fetch(`/delete-post/${slug}/`, {
                method: "DELETE",
                headers: {
                    "X-CSRFToken": "{{ csrf_token }}",
                },
            })
                .then((response) => {
                    if (response.ok) {
                        window.location.href = "/";
                    } else {
                        console.error(
                            "Error deleting post:",
                            response.statusText
                        );
                    }
                })
                .catch((error) => {
                    console.error("Error deleting post:", error);
                });
        }
    }
</script>

{% endblock %}

app/templates/home.html
{% extends "base.html" %}

{% block content %}
 
 
<form id="sear chForm" method="get"  class="form-inline mx-auto justify-content-center width-full mt-3">
    <div class="form-group mb-2">
        <label  for="id_query" class="sr-only">Search</label>
        <input type="text" name="query" placeholder="Search" required id="id_query"
            class="form-control">
    </div>
    <a href="{% url 'home' %}"  class="btn btn-primary mb-2">Search</a>
</form>

<div class="container w-full">
    <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-md-12 mt-3 ">
            {% for post in posts %}
            <a href="{% url 'post_detail' slug=post.slug  %}" style="text-decoration: none; color: black;" >
                <div class="card mb-4">
                    <div class="card-body">
                        <h2 class="card-title">{{ post.title|slice:":200" }}</h2>
                        <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                        <div>
                            <p class="card-text">
                                <span>{{ post.content|striptags|slice:":200" }}</span>...
                            </p>
                        </div>
                        </br>
                        <div>

                            <button class=" btn btn-primary"> 
                                Read More &rarr;
                            </button>
                        </div>
                    </div>

                </div>
            </a>
            {% endfor %}
        </div>
    </div>
</div>

<nav aria-label="Page navigation container">

<ul class="pagination justify-content-center">
    {% if posts.has_previous %}
    <li><a href="?page={{ posts.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
    {% endif %}
    {% if posts.has_next %}
    <li><a href="?page={{ posts.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

    {% endif %}
</ul>

{%endblock%}

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Design by foolishdeveloper.com -->
    <title>Login Page</title>
 
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
    <meta name="google" content="notranslate" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />
    <style>
        body {
            font-family: "Roboto", sans-serif;
            font-size: 17px;
            background-color: #fdfdfd;
        }

        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }

        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }

        .masthead {
            background: #3398E1;
            height: auto;
            padding-bottom: 15px;
            box-shadow: 0 16px 48px #E3E7EB;
            padding-top: 10px;
        }

        .card {
            box-shadow: 0 16px 48px #E3E7EB;
        }
    </style>
</head>
<body> 
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body text-center">
                        <h5 class="card-title mb-4">Login</h5>
                        <form method="post" action="{% url 'login_user' %}">
                            {% csrf_token %}
                            <div class="form-row mb-4">
                                <div class="col-4">
                                    <label for="username">Username:</label>
                                </div>
                                <div class="col-8">
                                    <input type="text" name="username" class="form-control" required>
                                </div>
                            </div>
                            <div class="form-row mb-4">
                                <div class="col-4">
                                    <label for="password">Password:</label>
                                </div>
                                <div class="col-8">
                                    <input type="password" name="password" class="form-control" required>
                                </div>
                            </div>
                            <button class="btn btn-primary btn-block" type="submit">Login</button>
                            {% if error_message %}
                                <p class="text-danger mt-3">{{ error_message }}</p>
                            {% endif %}
                        </form>
                        <p class="mt-3">Not registered? <a href="{% url 'register_user' %}">Signup</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    
     <!-- bootstrap scripts -->
     <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
     integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
 </script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
     integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
 </script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
     integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
 </script>
</body>
</html>

app/templates/post_detail.html
{% extends 'base.html' %} {% block content %}
    {% load crispy_forms_tags %}

    

    <div class="container">
        <div class="row">
            
            <div class="col-md-12 card mb-4  mt-3 left  top">
                <div class="card-body">
                    <h1>{% block title %} {{ post.title }} {% endblock title %}</h1>
                    {% if user_authenticated and post.author == request.user %} 
                    <a href="{% url 'edit_post' slug=post.slug  %}"  class="btn ">Edit &rarr;</a>
                    {% endif %}
                    <p class=" text-muted">{{ post.author }} | {{ post.created_on }}</p>
                    <p class="card-text ">{{ post.content | safe }}</p> 
                    {% if post.attachment %}
                        {% if post.attachment.url %}
                            {% if post.attachment.url|lower|slice:"-4:" == ".pdf" %}
                                <object data="{{ post.attachment.url }}" type="application/pdf" width="100%" height="600px">
                                    <p>It appears you don't have a PDF plugin for this browser. No biggie... you can <a href="{{ post.attachment.url }}">click here to download the PDF file.</a></p>
                                </object>
                            {% else %}
                                <p>Attachment: <a href="{{ post.attachment.url }}" target="_blank">{{ post.attachment.name }}</a></p>
                            {% endif %}
                        {% endif %}
                    {% endif %}
                </div>
            </div>
            <div class="col-md-12 card mb-4  mt-3 ">
                <div class="card-body">
                    {% if user_authenticated %} 
                        <h3>Leave a comment</h3>
                        <form method="post" style="margin-top: 1.3em;">
                            {% csrf_token %}
                                <textarea name="body" placeholder="Enter comment" style="width: 100%; border: none;" cols="align-items-center" id="id_body"></textarea>
                            <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
                        </form> 
                    {% else %}
                        <button  type="submit" name="edit_comment" value="{{ comment.id }}" ><a href="{% url 'login_user' %}">Login</a></button> to add comment
                        
                    {% endif %}
                    
                </div>
            </div>

            <div class="col-md-12 card mb-4  mt-3 ">
                <div class="card-body">
                    <!-- comments -->
                    {% with comments.count as total_comments %}
                        <h2>{{ total_comments }} comments</h2>

                        <p>
                    {% endwith %} {% for comment in comments %}
                        </p>

                        <div class="comments" style="padding: 10px;">
                            <p class="font-weight-bold">
                                {{ comment.author }}
                                <span class=" text-muted font-weight-light">
                                    {{ comment.created_on }}
                                </span>
                            </p>
                            {{ comment.body | linebreaks }}
                        </div>

                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

app/templates/register.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Design by foolishdeveloper.com -->
    <title>Signup Page</title>
 
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
    <meta name="google" content="notranslate" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />
    <!--Stylesheet-->
    <style media="screen">
     body {
            font-family: "Roboto", sans-serif;
            font-size: 17px;
            background-color: #fdfdfd;
        }

        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }

        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }

        .masthead {
            background: #3398E1;
            height: auto;
            padding-bottom: 15px;
            box-shadow: 0 16px 48px #E3E7EB;
            padding-top: 10px;
        }

        .card {
            box-shadow: 0 16px 48px #E3E7EB;
        }
 

        label {
            width: 40%;
        }  

        input {
            width: 59%;
        }
         
    </style>
</head>
<body>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body text-center">
                        <h5 class="card-title font-weight-bold">Register</h5>
                        <form method="post" action="{% url 'register_user' %}" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="container">
                                <div class="form-group">
                                    <label for="id_username">Username:</label>
                                    <input type="text" name="username"  class="form-control" maxlength="150" autofocus required>
                                </div>
                                <div class="form-group">
                                    <label for="id_email_address">Email:</label>
                                    <input type="email" name="email_address" class="form-control" autofocus required>
                                </div>
                                <div class="form-group">
                                    <label for="id_date_of_birth">Date of birth:</label>
                                    <input type="text" name="date_of_birth" class="form-control" id="id_date_of_birth">
                                </div>
                                <div class="form-group">
                                    <label for="id_profile_picture">Profile picture:</label>
                                    <input type="file" name="profile_picture" class="form-control-file" id="id_profile_picture">
                                </div>
                                <div class="form-group">
                                    <label for="id_password1">Password:</label>
                                    <input type="password" name="password1" class="form-control" autocomplete="new-password" required>
                                </div>
                                <div class="form-group">
                                    <label for="id_password2">Password confirmation:</label>
                                    <input type="password" name="password2" class="form-control" autocomplete="new-password" required>
                                </div>
    
                                {% if errors %}
                                <ul class="errorlist alert alert-warning">
                                    {% for field_errors in errors.values %}
                                    {% for error in field_errors %}
                                    <li>{{ error }}</li>
                                    {% endfor %}
                                    {% endfor %}
                                </ul>
                                {% endif %}
    
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary">Register</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    

    <script >
        var originalInput = document.getElementById('id_date_of_birth');
        originalInput.type = 'date';

    </script>

    <!-- bootstrap scripts -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
</script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
</script>
</body>
</html>